version: '3.8'

services:
  todo-server:
    container_name: todo-server
    image: todo-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - 'tds_data:/data/db'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
volumes:
  tds_data:
